/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @dfinity/caffeine-bindgen@0.1.0-beta.7.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface ScoreEntry {
    difficulty: string;
    level: bigint;
    score: bigint;
    timestamp: Time;
}
export interface PowerUp {
    id: string;
    duration: bigint;
    active: boolean;
    name: string;
    description: string;
    effect: string;
    timestamp?: Time;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface PlayerAchievements {
    name: string;
    achievements: Array<Achievement>;
    defeatedBossTypes: Array<string>;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface PlayerDesigns {
    name: string;
    unlockedDesigns: Array<SpaceshipDesign>;
    selectedDesign: string;
}
export interface PlayerPowerUps {
    activePowerUps: Array<PowerUp>;
    name: string;
}
export interface Achievement {
    id: string;
    name: string;
    unlocked: boolean;
    description: string;
    progress: bigint;
    target: bigint;
    timestamp?: Time;
    category: string;
    rarity: string;
}
export interface SpaceshipDesign {
    id: string;
    effects: string;
    name: string;
    color: string;
    unlocked: boolean;
    description: string;
    shape: string;
    unlockCondition: string;
}
export interface FileReference {
    hash: string;
    path: string;
}
export interface UserProfile {
    name: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobsToDelete(): Promise<Array<string>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<string>): Promise<void>;
    _caffeineStorageCreateCertificate(blob_hash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    activatePowerUp(name: string, powerUpId: string): Promise<boolean>;
    addScore(name: string, score: bigint, difficulty: string, level: bigint): Promise<boolean>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    checkAndUnlockDesigns(name: string): Promise<boolean>;
    deactivatePowerUp(name: string, powerUpId: string): Promise<boolean>;
    deleteScore(name: string): Promise<boolean>;
    dropFileReference(path: string): Promise<void>;
    getAchievements(name: string): Promise<PlayerAchievements | null>;
    getActivePowerUps(name: string): Promise<Array<PowerUp> | null>;
    getAllAchievements(): Promise<Array<PlayerAchievements>>;
    getAllDesigns(): Promise<Array<PlayerDesigns>>;
    getAllPowerUps(): Promise<Array<PlayerPowerUps>>;
    getAllRegisteredUsers(): Promise<Array<[Principal, UserProfile]>>;
    getAllScores(): Promise<Array<[string, ScoreEntry]>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDesigns(name: string): Promise<PlayerDesigns | null>;
    getFileReference(path: string): Promise<FileReference>;
    getScoresByDifficulty(difficulty: string): Promise<Array<[string, ScoreEntry]>>;
    getScoresByName(name: string): Promise<Array<[string, ScoreEntry]>>;
    getSelectedDesign(name: string): Promise<string | null>;
    getSelectedDesignForPrincipal(): Promise<string | null>;
    getTopScores(limit: bigint): Promise<Array<[string, ScoreEntry]>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initializeAccessControl(): Promise<void>;
    initializeAchievements(name: string): Promise<boolean>;
    initializeDesigns(name: string): Promise<boolean>;
    initializePowerUps(name: string): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    isUserRegistered(): Promise<boolean>;
    listFileReferences(): Promise<Array<FileReference>>;
    logoutUser(): Promise<void>;
    registerFileReference(path: string, hash: string): Promise<void>;
    registerUser(name: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    selectDesign(name: string, designId: string): Promise<boolean>;
    unlockDesign(name: string, designId: string): Promise<boolean>;
    updateAchievement(name: string, achievementId: string, progress: bigint): Promise<boolean>;
    updateBossMasterAchievement(name: string, bossType: string): Promise<boolean>;
    updateMagnetMasterAchievement(name: string, magnetCount: bigint): Promise<boolean>;
    updateMultipleAchievements(name: string, updates: Array<[string, bigint]>): Promise<boolean>;
    updateScore(name: string, newScore: bigint, newDifficulty: string, newLevel: bigint): Promise<boolean>;
}
import type { Achievement as _Achievement, PlayerAchievements as _PlayerAchievements, PlayerDesigns as _PlayerDesigns, PlayerPowerUps as _PlayerPowerUps, PowerUp as _PowerUp, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobsToDelete(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this.uploadFile, this.downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this.uploadFile, this.downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this.uploadFile, this.downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async activatePowerUp(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.activatePowerUp(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.activatePowerUp(arg0, arg1);
            return result;
        }
    }
    async addScore(arg0: string, arg1: bigint, arg2: string, arg3: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addScore(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addScore(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async checkAndUnlockDesigns(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.checkAndUnlockDesigns(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkAndUnlockDesigns(arg0);
            return result;
        }
    }
    async deactivatePowerUp(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivatePowerUp(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivatePowerUp(arg0, arg1);
            return result;
        }
    }
    async deleteScore(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteScore(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteScore(arg0);
            return result;
        }
    }
    async dropFileReference(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.dropFileReference(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.dropFileReference(arg0);
            return result;
        }
    }
    async getAchievements(arg0: string): Promise<PlayerAchievements | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAchievements(arg0);
                return from_candid_opt_n10(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAchievements(arg0);
            return from_candid_opt_n10(this.uploadFile, this.downloadFile, result);
        }
    }
    async getActivePowerUps(arg0: string): Promise<Array<PowerUp> | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivePowerUps(arg0);
                return from_candid_opt_n17(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivePowerUps(arg0);
            return from_candid_opt_n17(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAllAchievements(): Promise<Array<PlayerAchievements>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAchievements();
                return from_candid_vec_n21(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAchievements();
            return from_candid_vec_n21(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAllDesigns(): Promise<Array<PlayerDesigns>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDesigns();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDesigns();
            return result;
        }
    }
    async getAllPowerUps(): Promise<Array<PlayerPowerUps>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPowerUps();
                return from_candid_vec_n22(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPowerUps();
            return from_candid_vec_n22(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAllRegisteredUsers(): Promise<Array<[Principal, UserProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRegisteredUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRegisteredUsers();
            return result;
        }
    }
    async getAllScores(): Promise<Array<[string, ScoreEntry]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllScores();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllScores();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n25(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n25(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n26(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n26(this.uploadFile, this.downloadFile, result);
        }
    }
    async getDesigns(arg0: string): Promise<PlayerDesigns | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDesigns(arg0);
                return from_candid_opt_n28(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDesigns(arg0);
            return from_candid_opt_n28(this.uploadFile, this.downloadFile, result);
        }
    }
    async getFileReference(arg0: string): Promise<FileReference> {
        if (this.processError) {
            try {
                const result = await this.actor.getFileReference(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFileReference(arg0);
            return result;
        }
    }
    async getScoresByDifficulty(arg0: string): Promise<Array<[string, ScoreEntry]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getScoresByDifficulty(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScoresByDifficulty(arg0);
            return result;
        }
    }
    async getScoresByName(arg0: string): Promise<Array<[string, ScoreEntry]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getScoresByName(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScoresByName(arg0);
            return result;
        }
    }
    async getSelectedDesign(arg0: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSelectedDesign(arg0);
                return from_candid_opt_n29(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSelectedDesign(arg0);
            return from_candid_opt_n29(this.uploadFile, this.downloadFile, result);
        }
    }
    async getSelectedDesignForPrincipal(): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSelectedDesignForPrincipal();
                return from_candid_opt_n29(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSelectedDesignForPrincipal();
            return from_candid_opt_n29(this.uploadFile, this.downloadFile, result);
        }
    }
    async getTopScores(arg0: bigint): Promise<Array<[string, ScoreEntry]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopScores(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopScores(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n25(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n25(this.uploadFile, this.downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async initializeAchievements(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAchievements(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAchievements(arg0);
            return result;
        }
    }
    async initializeDesigns(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeDesigns(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeDesigns(arg0);
            return result;
        }
    }
    async initializePowerUps(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.initializePowerUps(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializePowerUps(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isUserRegistered(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isUserRegistered();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isUserRegistered();
            return result;
        }
    }
    async listFileReferences(): Promise<Array<FileReference>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFileReferences();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFileReferences();
            return result;
        }
    }
    async logoutUser(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logoutUser();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logoutUser();
            return result;
        }
    }
    async registerFileReference(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerFileReference(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerFileReference(arg0, arg1);
            return result;
        }
    }
    async registerUser(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async selectDesign(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.selectDesign(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.selectDesign(arg0, arg1);
            return result;
        }
    }
    async unlockDesign(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.unlockDesign(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlockDesign(arg0, arg1);
            return result;
        }
    }
    async updateAchievement(arg0: string, arg1: string, arg2: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAchievement(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAchievement(arg0, arg1, arg2);
            return result;
        }
    }
    async updateBossMasterAchievement(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBossMasterAchievement(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBossMasterAchievement(arg0, arg1);
            return result;
        }
    }
    async updateMagnetMasterAchievement(arg0: string, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMagnetMasterAchievement(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMagnetMasterAchievement(arg0, arg1);
            return result;
        }
    }
    async updateMultipleAchievements(arg0: string, arg1: Array<[string, bigint]>): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMultipleAchievements(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMultipleAchievements(arg0, arg1);
            return result;
        }
    }
    async updateScore(arg0: string, arg1: bigint, arg2: string, arg3: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateScore(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateScore(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
function from_candid_Achievement_n14(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Achievement): Achievement {
    return from_candid_record_n15(uploadFile, downloadFile, value);
}
function from_candid_PlayerAchievements_n11(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlayerAchievements): PlayerAchievements {
    return from_candid_record_n12(uploadFile, downloadFile, value);
}
function from_candid_PlayerPowerUps_n23(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlayerPowerUps): PlayerPowerUps {
    return from_candid_record_n24(uploadFile, downloadFile, value);
}
function from_candid_PowerUp_n19(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PowerUp): PowerUp {
    return from_candid_record_n20(uploadFile, downloadFile, value);
}
function from_candid_UserRole_n26(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n27(uploadFile, downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(uploadFile, downloadFile, value);
}
function from_candid_opt_n10(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PlayerAchievements]): PlayerAchievements | null {
    return value.length === 0 ? null : from_candid_PlayerAchievements_n11(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n16(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_PowerUp>]): Array<PowerUp> | null {
    return value.length === 0 ? null : from_candid_vec_n18(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n25(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PlayerDesigns]): PlayerDesigns | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    achievements: Array<_Achievement>;
    defeatedBossTypes: Array<string>;
}): {
    name: string;
    achievements: Array<Achievement>;
    defeatedBossTypes: Array<string>;
} {
    return {
        name: value.name,
        achievements: from_candid_vec_n13(uploadFile, downloadFile, value.achievements),
        defeatedBossTypes: value.defeatedBossTypes
    };
}
function from_candid_record_n15(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    unlocked: boolean;
    description: string;
    progress: bigint;
    target: bigint;
    timestamp: [] | [_Time];
    category: string;
    rarity: string;
}): {
    id: string;
    name: string;
    unlocked: boolean;
    description: string;
    progress: bigint;
    target: bigint;
    timestamp?: Time;
    category: string;
    rarity: string;
} {
    return {
        id: value.id,
        name: value.name,
        unlocked: value.unlocked,
        description: value.description,
        progress: value.progress,
        target: value.target,
        timestamp: record_opt_to_undefined(from_candid_opt_n16(uploadFile, downloadFile, value.timestamp)),
        category: value.category,
        rarity: value.rarity
    };
}
function from_candid_record_n20(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    duration: bigint;
    active: boolean;
    name: string;
    description: string;
    effect: string;
    timestamp: [] | [_Time];
}): {
    id: string;
    duration: bigint;
    active: boolean;
    name: string;
    description: string;
    effect: string;
    timestamp?: Time;
} {
    return {
        id: value.id,
        duration: value.duration,
        active: value.active,
        name: value.name,
        description: value.description,
        effect: value.effect,
        timestamp: record_opt_to_undefined(from_candid_opt_n16(uploadFile, downloadFile, value.timestamp))
    };
}
function from_candid_record_n24(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    activePowerUps: Array<_PowerUp>;
    name: string;
}): {
    activePowerUps: Array<PowerUp>;
    name: string;
} {
    return {
        activePowerUps: from_candid_vec_n18(uploadFile, downloadFile, value.activePowerUps),
        name: value.name
    };
}
function from_candid_record_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(uploadFile, downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(uploadFile, downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n27(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n13(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Achievement>): Array<Achievement> {
    return value.map((x)=>from_candid_Achievement_n14(uploadFile, downloadFile, x));
}
function from_candid_vec_n18(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PowerUp>): Array<PowerUp> {
    return value.map((x)=>from_candid_PowerUp_n19(uploadFile, downloadFile, x));
}
function from_candid_vec_n21(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PlayerAchievements>): Array<PlayerAchievements> {
    return value.map((x)=>from_candid_PlayerAchievements_n11(uploadFile, downloadFile, x));
}
function from_candid_vec_n22(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PlayerPowerUps>): Array<PlayerPowerUps> {
    return value.map((x)=>from_candid_PlayerPowerUps_n23(uploadFile, downloadFile, x));
}
function to_candid_UserRole_n8(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(uploadFile, downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(uploadFile, downloadFile, value);
}
function to_candid_opt_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(uploadFile, downloadFile, value));
}
function to_candid_record_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n9(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}