/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @dfinity/caffeine-bindgen@0.1.0-beta.7.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Achievement {
  'id' : string,
  'name' : string,
  'unlocked' : boolean,
  'description' : string,
  'progress' : bigint,
  'target' : bigint,
  'timestamp' : [] | [Time],
  'category' : string,
  'rarity' : string,
}
export interface FileReference { 'hash' : string, 'path' : string }
export interface PlayerAchievements {
  'name' : string,
  'achievements' : Array<Achievement>,
  'defeatedBossTypes' : Array<string>,
}
export interface PlayerDesigns {
  'name' : string,
  'unlockedDesigns' : Array<SpaceshipDesign>,
  'selectedDesign' : string,
}
export interface PlayerPowerUps {
  'activePowerUps' : Array<PowerUp>,
  'name' : string,
}
export interface PowerUp {
  'id' : string,
  'duration' : bigint,
  'active' : boolean,
  'name' : string,
  'description' : string,
  'effect' : string,
  'timestamp' : [] | [Time],
}
export interface ScoreEntry {
  'difficulty' : string,
  'level' : bigint,
  'score' : bigint,
  'timestamp' : Time,
}
export interface SpaceshipDesign {
  'id' : string,
  'effects' : string,
  'name' : string,
  'color' : string,
  'unlocked' : boolean,
  'description' : string,
  'shape' : string,
  'unlockCondition' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<string>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<string>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'activatePowerUp' : ActorMethod<[string, string], boolean>,
  'addScore' : ActorMethod<[string, bigint, string, bigint], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkAndUnlockDesigns' : ActorMethod<[string], boolean>,
  'deactivatePowerUp' : ActorMethod<[string, string], boolean>,
  'deleteScore' : ActorMethod<[string], boolean>,
  'dropFileReference' : ActorMethod<[string], undefined>,
  'getAchievements' : ActorMethod<[string], [] | [PlayerAchievements]>,
  'getActivePowerUps' : ActorMethod<[string], [] | [Array<PowerUp>]>,
  'getAllAchievements' : ActorMethod<[], Array<PlayerAchievements>>,
  'getAllDesigns' : ActorMethod<[], Array<PlayerDesigns>>,
  'getAllPowerUps' : ActorMethod<[], Array<PlayerPowerUps>>,
  'getAllRegisteredUsers' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getAllScores' : ActorMethod<[], Array<[string, ScoreEntry]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDesigns' : ActorMethod<[string], [] | [PlayerDesigns]>,
  'getFileReference' : ActorMethod<[string], FileReference>,
  'getScoresByDifficulty' : ActorMethod<[string], Array<[string, ScoreEntry]>>,
  'getScoresByName' : ActorMethod<[string], Array<[string, ScoreEntry]>>,
  'getSelectedDesign' : ActorMethod<[string], [] | [string]>,
  'getSelectedDesignForPrincipal' : ActorMethod<[], [] | [string]>,
  'getTopScores' : ActorMethod<[bigint], Array<[string, ScoreEntry]>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'initializeAchievements' : ActorMethod<[string], boolean>,
  'initializeDesigns' : ActorMethod<[string], boolean>,
  'initializePowerUps' : ActorMethod<[string], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isUserRegistered' : ActorMethod<[], boolean>,
  'listFileReferences' : ActorMethod<[], Array<FileReference>>,
  'logoutUser' : ActorMethod<[], undefined>,
  'registerFileReference' : ActorMethod<[string, string], undefined>,
  'registerUser' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'selectDesign' : ActorMethod<[string, string], boolean>,
  'unlockDesign' : ActorMethod<[string, string], boolean>,
  'updateAchievement' : ActorMethod<[string, string, bigint], boolean>,
  'updateBossMasterAchievement' : ActorMethod<[string, string], boolean>,
  'updateMagnetMasterAchievement' : ActorMethod<[string, bigint], boolean>,
  'updateMultipleAchievements' : ActorMethod<
    [string, Array<[string, bigint]>],
    boolean
  >,
  'updateScore' : ActorMethod<[string, bigint, string, bigint], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];