/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @dfinity/caffeine-bindgen@0.1.0-beta.7.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Achievement = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'unlocked' : IDL.Bool,
  'description' : IDL.Text,
  'progress' : IDL.Nat,
  'target' : IDL.Nat,
  'timestamp' : IDL.Opt(Time),
  'category' : IDL.Text,
  'rarity' : IDL.Text,
});
export const PlayerAchievements = IDL.Record({
  'name' : IDL.Text,
  'achievements' : IDL.Vec(Achievement),
  'defeatedBossTypes' : IDL.Vec(IDL.Text),
});
export const PowerUp = IDL.Record({
  'id' : IDL.Text,
  'duration' : IDL.Nat,
  'active' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'effect' : IDL.Text,
  'timestamp' : IDL.Opt(Time),
});
export const SpaceshipDesign = IDL.Record({
  'id' : IDL.Text,
  'effects' : IDL.Text,
  'name' : IDL.Text,
  'color' : IDL.Text,
  'unlocked' : IDL.Bool,
  'description' : IDL.Text,
  'shape' : IDL.Text,
  'unlockCondition' : IDL.Text,
});
export const PlayerDesigns = IDL.Record({
  'name' : IDL.Text,
  'unlockedDesigns' : IDL.Vec(SpaceshipDesign),
  'selectedDesign' : IDL.Text,
});
export const PlayerPowerUps = IDL.Record({
  'activePowerUps' : IDL.Vec(PowerUp),
  'name' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ScoreEntry = IDL.Record({
  'difficulty' : IDL.Text,
  'level' : IDL.Int,
  'score' : IDL.Int,
  'timestamp' : Time,
});
export const FileReference = IDL.Record({
  'hash' : IDL.Text,
  'path' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'activatePowerUp' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'addScore' : IDL.Func([IDL.Text, IDL.Int, IDL.Text, IDL.Int], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkAndUnlockDesigns' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deactivatePowerUp' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'deleteScore' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'dropFileReference' : IDL.Func([IDL.Text], [], []),
  'getAchievements' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PlayerAchievements)],
      ['query'],
    ),
  'getActivePowerUps' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Vec(PowerUp))],
      ['query'],
    ),
  'getAllAchievements' : IDL.Func([], [IDL.Vec(PlayerAchievements)], ['query']),
  'getAllDesigns' : IDL.Func([], [IDL.Vec(PlayerDesigns)], ['query']),
  'getAllPowerUps' : IDL.Func([], [IDL.Vec(PlayerPowerUps)], ['query']),
  'getAllRegisteredUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getAllScores' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, ScoreEntry))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDesigns' : IDL.Func([IDL.Text], [IDL.Opt(PlayerDesigns)], ['query']),
  'getFileReference' : IDL.Func([IDL.Text], [FileReference], ['query']),
  'getScoresByDifficulty' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Text, ScoreEntry))],
      ['query'],
    ),
  'getScoresByName' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Text, ScoreEntry))],
      ['query'],
    ),
  'getSelectedDesign' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'getSelectedDesignForPrincipal' : IDL.Func(
      [],
      [IDL.Opt(IDL.Text)],
      ['query'],
    ),
  'getTopScores' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Tuple(IDL.Text, ScoreEntry))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'initializeAchievements' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'initializeDesigns' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'initializePowerUps' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isUserRegistered' : IDL.Func([], [IDL.Bool], ['query']),
  'listFileReferences' : IDL.Func([], [IDL.Vec(FileReference)], ['query']),
  'logoutUser' : IDL.Func([], [], []),
  'registerFileReference' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'registerUser' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'selectDesign' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'unlockDesign' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'updateAchievement' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Bool], []),
  'updateBossMasterAchievement' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updateMagnetMasterAchievement' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Bool],
      [],
    ),
  'updateMultipleAchievements' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      [IDL.Bool],
      [],
    ),
  'updateScore' : IDL.Func(
      [IDL.Text, IDL.Int, IDL.Text, IDL.Int],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Achievement = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'unlocked' : IDL.Bool,
    'description' : IDL.Text,
    'progress' : IDL.Nat,
    'target' : IDL.Nat,
    'timestamp' : IDL.Opt(Time),
    'category' : IDL.Text,
    'rarity' : IDL.Text,
  });
  const PlayerAchievements = IDL.Record({
    'name' : IDL.Text,
    'achievements' : IDL.Vec(Achievement),
    'defeatedBossTypes' : IDL.Vec(IDL.Text),
  });
  const PowerUp = IDL.Record({
    'id' : IDL.Text,
    'duration' : IDL.Nat,
    'active' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'effect' : IDL.Text,
    'timestamp' : IDL.Opt(Time),
  });
  const SpaceshipDesign = IDL.Record({
    'id' : IDL.Text,
    'effects' : IDL.Text,
    'name' : IDL.Text,
    'color' : IDL.Text,
    'unlocked' : IDL.Bool,
    'description' : IDL.Text,
    'shape' : IDL.Text,
    'unlockCondition' : IDL.Text,
  });
  const PlayerDesigns = IDL.Record({
    'name' : IDL.Text,
    'unlockedDesigns' : IDL.Vec(SpaceshipDesign),
    'selectedDesign' : IDL.Text,
  });
  const PlayerPowerUps = IDL.Record({
    'activePowerUps' : IDL.Vec(PowerUp),
    'name' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ScoreEntry = IDL.Record({
    'difficulty' : IDL.Text,
    'level' : IDL.Int,
    'score' : IDL.Int,
    'timestamp' : Time,
  });
  const FileReference = IDL.Record({ 'hash' : IDL.Text, 'path' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'activatePowerUp' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'addScore' : IDL.Func(
        [IDL.Text, IDL.Int, IDL.Text, IDL.Int],
        [IDL.Bool],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkAndUnlockDesigns' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deactivatePowerUp' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'deleteScore' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'dropFileReference' : IDL.Func([IDL.Text], [], []),
    'getAchievements' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PlayerAchievements)],
        ['query'],
      ),
    'getActivePowerUps' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Vec(PowerUp))],
        ['query'],
      ),
    'getAllAchievements' : IDL.Func(
        [],
        [IDL.Vec(PlayerAchievements)],
        ['query'],
      ),
    'getAllDesigns' : IDL.Func([], [IDL.Vec(PlayerDesigns)], ['query']),
    'getAllPowerUps' : IDL.Func([], [IDL.Vec(PlayerPowerUps)], ['query']),
    'getAllRegisteredUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getAllScores' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, ScoreEntry))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDesigns' : IDL.Func([IDL.Text], [IDL.Opt(PlayerDesigns)], ['query']),
    'getFileReference' : IDL.Func([IDL.Text], [FileReference], ['query']),
    'getScoresByDifficulty' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Text, ScoreEntry))],
        ['query'],
      ),
    'getScoresByName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Text, ScoreEntry))],
        ['query'],
      ),
    'getSelectedDesign' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'getSelectedDesignForPrincipal' : IDL.Func(
        [],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getTopScores' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Tuple(IDL.Text, ScoreEntry))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'initializeAchievements' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'initializeDesigns' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'initializePowerUps' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isUserRegistered' : IDL.Func([], [IDL.Bool], ['query']),
    'listFileReferences' : IDL.Func([], [IDL.Vec(FileReference)], ['query']),
    'logoutUser' : IDL.Func([], [], []),
    'registerFileReference' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'registerUser' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'selectDesign' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'unlockDesign' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'updateAchievement' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Bool],
        [],
      ),
    'updateBossMasterAchievement' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateMagnetMasterAchievement' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Bool],
        [],
      ),
    'updateMultipleAchievements' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        [IDL.Bool],
        [],
      ),
    'updateScore' : IDL.Func(
        [IDL.Text, IDL.Int, IDL.Text, IDL.Int],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };